_3_Auth_Module_AtoZ/Component/AccountSettingsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_Auth_Module_AtoZ.Component
{
    public class AccountSettingsViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            //___ 1 ___
            //if you gave name in  View  then  Name shuld defined in Component folder for View
            //return View("AccountSettings");

            //___ 2 ___
            //if you did not give name in View ---> Then  Name of View will be      default.cshtml
            return View();
        }
    }
}

_3_Auth_Module_AtoZ/Component/IdentityProfileComponent/ProfileViewComponent.cs
using _3_Auth_Module_AtoZ.ViewModel;
using DAL.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace _3_Auth_Module_AtoZ.Component.IdentityProfileComponent
{
    public class ProfileViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public ProfileViewComponent(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = new ProfileViewModel
            {
                UserName = user.UserName,
                Email = user.Email
                // Add any additional profile properties you want to display
            };
            return View("/Views/Shared/Components/IdentityProfileComponent/Profile/Profile.cshtml", model);
        }


    }
}

_3_Auth_Module_AtoZ/Component/NavbarViewComponent.cs
using DAL.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Security.Claims;
using _3_Auth_Module_AtoZ.ViewModel;

namespace _3_Auth_Module_AtoZ.Component
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;

        public NavbarViewComponent(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var navbarViewModel = new NavbarViewModel();

            if (signInManager.IsSignedIn((ClaimsPrincipal)User))
            {
                var user = await userManager.GetUserAsync((ClaimsPrincipal)User);
                var profilePicture = user.profileImage;

                navbarViewModel.IsSignedIn = true;
                navbarViewModel.ProfilePicture = profilePicture;
                navbarViewModel.UserName = User.Identity.Name;

                var isInRole = await userManager.IsInRoleAsync(user, "Admin"); // Replace "Admin" with the desired role name
                navbarViewModel.IsAdmin = isInRole;
            }

            return View("Navbar", navbarViewModel);
        }
    }
}

_3_Auth_Module_AtoZ/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_Auth_Module_AtoZ.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

_3_Auth_Module_AtoZ/Controllers/RoleController.cs
using _3_Auth_Module_AtoZ.ViewModel;
using DAL.Data;
using DML._3_Auth_Module;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace _3_Auth_Module_AtoZ.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly dbContext context;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        

        public RoleController(RoleManager<IdentityRole> roleManager
                    ,UserManager<ApplicationUser> userManager
                    , dbContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            this.context = context;
        }

        /*_________________________ Master View _______________________*/
        public async Task<IActionResult> UserList()
        {
            var users = await _userManager.Users.ToListAsync();
            var viewModel = new List<UserViewModel>();

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                var claims = await _userManager.GetClaimsAsync(user);

                var userViewModel = new UserViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    Roles = roles.ToList(),
                    Claims = claims.Select(c => new ClaimViewModel { Type = c.Type, Value = c.Value }).ToList()
                };

                viewModel.Add(userViewModel);
            }

            return View(viewModel);
        }


        //_______________ Manage Roles _______________________
        #region Assign_Roles
        [HttpGet]
        public async Task<IActionResult> EditRolesAssign(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            var allRoles = _roleManager.Roles.Select(r => new RoleViewModel { RoleName = r.Name }).ToList();

            var userRoles = await _userManager.GetRolesAsync(user);
            foreach (var role in allRoles)
            {
                role.IsSelected = userRoles.Contains(role.RoleName);
            }

            var viewModel = new EditRolesViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                AllRoles = allRoles
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateRolesAssign(EditRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                return NotFound();
            }

            var selectedRoles = model.SelectedRoles ?? new List<string>();
            var userRoles = await _userManager.GetRolesAsync(user);

            var rolesToAdd = selectedRoles.Except(userRoles);
            var rolesToRemove = userRoles.Except(selectedRoles);

            await _userManager.AddToRolesAsync(user, rolesToAdd);
            await _userManager.RemoveFromRolesAsync(user, rolesToRemove);

            return RedirectToAction("UserList");
        }

        #endregion

        /*_______________ Roles CRUD ______________________*/
        #region Assign_Roles
        public IActionResult Roles()
        {
            var roles = _roleManager.Roles.OrderBy(x=>x.Name).ToList();
            return View(roles);
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole { Name = model.RoleName };
                var result = await _roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Roles"); // Redirect to the desired page
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                return NotFound();
            }

            var model = new EditRoleViewModel { RoleId = role.Id, RoleName = role.Name };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.RoleId);
                if (role == null)
                {
                    return NotFound();
                }

                role.Name = model.RoleName;
                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Roles"); // Redirect to the desired page
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }
        
        public async Task<IActionResult> DeleteRole(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                return NotFound();
            }

            var result = await _roleManager.DeleteAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("Roles"); // Redirect to the desired page
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(roleId);
        }
        #endregion

        //_______________ Manage Claims _______________________
        #region Manage_Claims

        //__________ 1 Static Claims _____________
        #region Static Claims
        //1. create ClaimStore Class    -- to Store Claim  staticly -- in DML
        //2. dd UserClaimsViewModel  to get ---> userId , staticClaims (userClaims)
        //3. In IdentityDatabase ---> Assign Claims Stored in  AspNetUserClaims tables (id,UserId,ClaimType,ClaimValue)
        [HttpGet]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            // UserManager service GetClaimsAsync method gets all the current claims of the user
            var existingUserClaims = await _userManager.GetClaimsAsync(user);

            var model = new UserClaimsViewModel
            {
                UserId = userId,
                UserName = user.UserName
            };

            // Loop through each claim we have in our application
            foreach (Claim claim in ClaimsStore.AllClaims)  //3 bar loop chlaa gaa
            {
                UserClaim userClaim = new UserClaim
                {
                    ClaimType = claim.Type
                };

                // If the user has the claim, set IsSelected property to true, so the checkbox
                // next to the claim is checked on the UI
                if (existingUserClaims.Any(c => c.Type == claim.Type))
                {
                    userClaim.IsSelected = true;
                }

                model.Cliams.Add(userClaim); //1st list dd , 2nd list ,  3rd list
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ManageUserClaims(UserClaimsViewModel model)
        {
            var user = await _userManager.FindByIdAsync(model.UserId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {model.UserId} cannot be found";
                return View("NotFound");
            }

            // Get all the user existing claims and delete them
            var claims = await _userManager.GetClaimsAsync(user);
            var result = await _userManager.RemoveClaimsAsync(user, claims);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing claims");
                return View(model);
            }

            // Add all the claims that are selected on the UI
            result = await _userManager.AddClaimsAsync(user,
                model.Cliams.Where(c => c.IsSelected).Select(c => new Claim(c.ClaimType, c.ClaimType)));

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected claims to user");
                return View(model);
            }

            return RedirectToAction("UserList");

        }

        #endregion

        //__________ 2 Database Claims _____________
        #region Database Claims
        //Create ClaimModel and Add to Database
        //Add some  Claims in Database Table
        //then the others Step will be same as Above
        [HttpGet]
        public async Task<IActionResult> ManageUserClaimsDb(string userId)
        {

_3_Auth_Module_AtoZ/Views/Shared/Components/Navbar/Navbar.cshtml
@model NavbarViewModel

<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>

    @if (Model.IsSignedIn)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
        </li>
    }

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
</ul>

@if (Model.IsSignedIn)
{
    <ul class="navbar-nav flex-lg-grow-0">
        <li>
            <a id="resetPasswordLink" style ="cursor:pointer" class="nav-link text-dark">Reset Password</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark">
                @{
                    var imgPath = @Model.ProfilePicture != null ? "~/@Model.ProfilePicture" : "/images/plache.png";        
                }
                <img src="@imgPath" width="30px" height="30px" class="rounded-circle" />
            </a>
        </li>
        <li class="nav-item">
            @{
                string userName= Model.UserName.Substring(0, 6);
            }
            <a class="nav-link text-dark" asp-action="Index" asp-controller="Profile"> @userName</a>
        </li>
        @if (Model.IsAdmin)
        {
            <!--
                        insert into AspNetRoles values
            ('6843f2b7-2a4f-4e9a-8e7e-8ab3b52e3a5d','Admin','ADMIN','85d56612-98bb-4457-aa97-d3cd5e198e21'),
            ('2536f4a3-d10d-47d1-83a4-15dcafe27a10','User','USER','0f519a79-7aee-4edc-a582-1277ce57bc53'),
            ('a59348b8-3961-4ce3-93ce-aae6b355c2c3','Employee','EMPLOYEE','9a94c63f-8b7e-48e4-9a94-65f81ad05fa8'),
            ('9d9a52e4-4a0a-42db-8ed4-5e63f424a5bc','Manager','MANAGER','7c5a1f38-1c9d-42f6-aa9b-3e769ef2c32a')

                        insert into AspNetUserRoles
            values ('3fe0a76e-90a2-4f9c-a46d-7695284f7181','6843f2b7-2a4f-4e9a-8e7e-8ab3b52e3a5d') -- Saqib ,Admin
            -->

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                    Roles
                </a>
                <div class="dropdown-menu">
                    <a class="nav-link text-warning" asp-area="" asp-controller="Role" asp-action="UserList">UserList</a>
                    <a class="nav-link text-warning" asp-area="" asp-controller="Role" asp-action="Roles">Roles</a>
                    <a class="nav-link text-warning" asp-area="" asp-controller="Role" asp-action="Claims">Claims</a>
                </div>
            </li>
        }
        <li class="nav-item">
            <a class="nav-link text-warning" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
        </li>
    </ul>
}
else
{
    <ul class="navbar-nav flex-lg-grow-0">
        <li class="nav-item">
            <a class="nav-link text-primary" asp-area="" asp-controller="Account" asp-action="Register">SignUp</a>
        </li>
        <li class="nav-item">
            <a class="nav-link  text-primary" asp-area="" asp-controller="Account" asp-action="Login">SignIn</a>
        </li>
    </ul>
}
<script>
    document.getElementById("resetPasswordLink").addEventListener("click", function (event) {
        event.preventDefault(); // Prevent the default navigation behavior of the anchor tag

        // Create a form element
        var form = document.createElement("form");
        form.setAttribute("method", "post");
        form.setAttribute("action", "@Url.Action("ForgotPasswordJs", "Account")");

        // Create an input element for the email
        var emailInput = document.createElement("input");
        emailInput.setAttribute("type", "hidden");
        emailInput.setAttribute("name", "Email");
        emailInput.setAttribute("value", "@User.Identity.Name");

        // Add the input element to the form
        form.appendChild(emailInput);

        // Append the form to the document body and submit it
        document.body.appendChild(form);
        form.submit();
    });
</script>