_1_Authentication_Authorization/Component/NavbarViewComponent.cs
using DAL.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Security.Claims;
using _1_Authentication_Authorization.ViewModel;

namespace _1_Authentication_Authorization.Component
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;

        public NavbarViewComponent(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var navbarViewModel = new NavbarViewModel();

            if (signInManager.IsSignedIn((ClaimsPrincipal)User))
            {
                var user = await userManager.GetUserAsync((ClaimsPrincipal)User);
                var profilePicture = user.profileImage;

                navbarViewModel.IsSignedIn = true;
                navbarViewModel.ProfilePicture = profilePicture;
                navbarViewModel.UserName = User.Identity.Name;

                var isInRole = await userManager.IsInRoleAsync(user, "Admin"); // Replace "Admin" with the desired role name
                navbarViewModel.IsAdmin = isInRole;
            }

            return View("Navbar", navbarViewModel);
        }
    }
}

_1_Authentication_Authorization/Controllers/ProductsController.cs
using _3_Authentication_Authorization_Other_Project.Models;
using DAL.Data;
using DML._1_clsAuthentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace _1_Authentication_Authorization.Controllers
{

    //*******************  2. Controller Level Authorize  *******************
    [Authorize]
    public class ProductsController : Controller
    {

        private dbContext context;
        public ProductsController(dbContext context)
        {
            this.context = context;
        }

        //______________________ Index _________________________

        //*******************  2. Controller Level Authorize  *******************
        [AllowAnonymous]
        public IActionResult Index()
        {
            var list = context.clProductsAuthentication.ToList();
            return View(list);
        }


        //______________________ Create _________________________

        //*******************  1. Action Level Authorize  *******************
        //[Authorize]
        [Authorize("Employee")]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize("Admin")]
        [HttpPost]
        public IActionResult Create(clsProductAuthentication product)
        {
            context.clProductsAuthentication.Add(product);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

_1_Authentication_Authorization/Controllers/RoleController.cs
using _1_Authentication_Authorization.ViewModel;
using DAL.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Threading.Tasks;

namespace _1_Authentication_Authorization.Controllers
{
    [Authorize(Roles = "Admin")]  //roles or User  Editor ko nhin danaa
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }


        public IActionResult Index()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([MinLength(2), Required] string name)
        {
            //ViewBag.roleList = new SelectList(roleManager.Roles,"Name","Id");
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
            }
            return View();
        }


        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            await roleManager.DeleteAsync(role);
            TempData["danger"] = "Role Deleted Success";
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<ApplicationUser> members = new List<ApplicationUser>();
            List<ApplicationUser> nonMembers = new List<ApplicationUser>();
            foreach (ApplicationUser user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }

            return View(new AssignRoleViewModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AssignRoleViewModel roleEdit)
        {
            IdentityResult result;

            //___ addIds ____
            foreach (string userId in roleEdit.AddIds ?? new string[] { })
            {
                ApplicationUser user = await userManager.FindByIdAsync(userId);
                result = await userManager.AddToRoleAsync(user, roleEdit.RoleName);
            }

            //___ RemoveIds ____
            foreach (string userId in roleEdit.DeleteIds ?? new string[] { })
            {
                ApplicationUser user = await userManager.FindByIdAsync(userId);
                result = await userManager.RemoveFromRoleAsync(user, roleEdit.RoleName);
            }

            return Redirect(Request.Headers["Referer"].ToString());
        }


    }
}

_1_Authentication_Authorization/Views/Shared/Components/Navbar/Navbar.cshtml
@model NavbarViewModel

<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>

    @if (Model.IsSignedIn)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
        </li>
    }

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
</ul>

@if (Model.IsSignedIn)
{
    <ul class="navbar-nav flex-lg-grow-0">
        <li class="nav-item">
            <a class="nav-link text-dark">
                <img src="~/@Model.ProfilePicture" width="30px" height="30px" class="rounded-circle" />
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark"> @Model.UserName</a>
        </li>
        @if (Model.IsAdmin)
        {
            <!--
                        insert into AspNetRoles values
            ('6843f2b7-2a4f-4e9a-8e7e-8ab3b52e3a5d','Admin','ADMIN','85d56612-98bb-4457-aa97-d3cd5e198e21'),
            ('2536f4a3-d10d-47d1-83a4-15dcafe27a10','User','USER','0f519a79-7aee-4edc-a582-1277ce57bc53'),
            ('a59348b8-3961-4ce3-93ce-aae6b355c2c3','Employee','EMPLOYEE','9a94c63f-8b7e-48e4-9a94-65f81ad05fa8'),
            ('9d9a52e4-4a0a-42db-8ed4-5e63f424a5bc','Manager','MANAGER','7c5a1f38-1c9d-42f6-aa9b-3e769ef2c32a')

                        insert into AspNetUserRoles
            values ('3fe0a76e-90a2-4f9c-a46d-7695284f7181','6843f2b7-2a4f-4e9a-8e7e-8ab3b52e3a5d') -- Saqib ,Admin
            -->

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                    Roles
                </a>
                <div class="dropdown-menu">
                    <a class="nav-link text-warning" asp-area="" asp-controller="Role" asp-action="Index">UserRoles</a>
                    <a class="nav-link text-warning" asp-area="" asp-controller="Role" asp-action="RoleList">Roles</a>
                    <a class="nav-link text-warning" asp-area="" asp-controller="Role" asp-action="CreateRole">Add Roles</a>
                    <a class="nav-link text-warning" asp-area="" asp-controller="Role" asp-action="AssignRole">Assign Roles</a>
                </div>
            </li>

            <li class="nav-item">

                

            </li>
        }
        <li class="nav-item">
            <a class="nav-link text-warning" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
        </li>
    </ul>
}
else
{
    <ul class="navbar-nav flex-lg-grow-0">
        <li class="nav-item">
            <a class="nav-link text-primary" asp-area="" asp-controller="Account" asp-action="Signup">SignUp</a>
        </li>
        <li class="nav-item">
            <a class="nav-link  text-primary" asp-area="" asp-controller="Account" asp-action="Signin">SignIn</a>
        </li>
    </ul>
}